task 5
Hrihor-Dmytro/nodejs-homework-REST-API pull request #4
Opened 2023-02-17 21:24 UTC by Hrihor-Dmytro

Доброї ночі. 5 домашня робота на перевірку. Дякую

2023-02-18 09:08 UTC, Eastvarga requested changes
Є зауваження

2023-02-18 09:08 UTC, Eastvarga commented on controllers/users.js
> +    const [, extention] = filename.split(".");
погане рішення бо якщо ім'я має кому та не одну, то що буде у extention?

2023-02-18 09:08 UTC, Eastvarga commented on controllers/users.js
> +    const avatarURL = path.join("avatars", newFileName);
невірно, ваш код генерує невірні строки avatarURL 
"avatars\myFile.jpg" - коли запускається  у системі Віндовс.
Ваш код не повинен залежати від системи у якій працює, до тогож ця строка ніяк не схожа на
http://locahost:<порт>/avatars/<ім'я файлу з розширенням>

2023-02-18 20:55 UTC, Hrihor-Dmytro commented on controllers/users.js
> +    const [, extention] = filename.split(".");
пофиксил

2023-02-18 20:55 UTC, Hrihor-Dmytro commented on controllers/users.js
> +    const avatarURL = path.join("avatars", newFileName);
исправил

2023-02-19 11:13 UTC, Eastvarga requested changes
Є критичне зауваження

2023-02-19 11:13 UTC, Eastvarga commented on controllers/users.js
> +    const avatarURL = path.join(avatarsDir, newFileName);
Ви не зробили вірних висновків з попереднього зауваження.
генеруйте url строку згідно з завданням ДЗ - не користуйтесь path.join для цього.
модуль path використовується лише для роботи з файловою системою.
У avatarURL має генеруватись строка згідно ДЗ http://locahost:<порт>/avatars/<ім'я файлу з розширенням>
тобто avatarURL =  \`http://locahost:${порт}/avatars/${ім'я файлу з розширенням}`

2023-02-19 13:03 UTC, Hrihor-Dmytro commented on controllers/users.js
> +    const avatarURL = path.join("avatars", newFileName);
сделал строкой

2023-02-19 13:03 UTC, Hrihor-Dmytro commented on controllers/users.js
> +    const avatarURL = path.join(avatarsDir, newFileName);
сделал строкой

2023-02-19 15:25 UTC, Eastvarga approved these changes

2023-02-19 15:25 UTC, Eastvarga commented on controllers/users.js
> +    const avatarURL = `http://localhost:3000/avatars/${newFileName}`;
Чому порт вказан статикою?
Хост  url link повинен залежати від того де запускається Ваш сервер, отже ваша строка має складатись з елементів залежних від хосту сервера та назви файла, сама тека аватар, по логиці статична.
Отже варто не статично вказувати порт а  дінамічно відповідно до PORT.

2023-02-19 15:25 UTC, merged